---
# Tasks file for common
- include_vars: ../../credentials.yml

- name: apt-get update
  apt: update_cache=true

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - whois
    - vim
    - unzip
    - curl
    - rsync
    - wget
    - sendmail
    - git
    - nfs-common

- name: create user
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    password: no
    state: present
    createhome: yes
  with_items: "{{ ssh_users }}"

- name: Add ssh user keys
  authorized_key: 
    user: "{{ item.name }}"  
    key: "{{ item.key }}" 
    state: present
  with_items: "{{ ssh_users }}"

#- name: Add www-data user
#  user:
#    name: "www-data"
#    shell: /bin/bash
#    password: no
#    state: present

- name: Ensure root .ssh directory exists.
  file: 
    dest: "/root/.ssh"
    mode: 0700 
    owner: www-data
    state: directory

- name: Install ssh key
  copy: 
    content: "{{ lookup('file', '../files/root_id_rsa') }}"
    dest: "/root/.ssh/id_rsa"
    mode: 0600
    owner: root

- name: add ssh config
  copy:
    content: "{{ lookup('file', '../files/root_config_file') }}"
    dest: "/root/.ssh/config"
    mode: 0644
    owner: root

- name: Set jenkins key 
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '../files/jenkins.pub') }}"

#- name: install datadog agent
#  shell: agent_install.sh
#  args:
#    chdir: /home/ubuntu
