---
# tasks file for mumzworld-php
- name: apt-get update
  apt: update_cache=true

- name: add repo
  apt_repository:
      repo: 'ppa:ondrej/php'

- name: apt-get update
  apt: update_cache=true

- name: uninstall php7
  apt: name=php7* state=absent purge=yes force=yes update_cache=true
  sudo: yes

- name: Install php5.6
  apt: name={{ item }} state=present update_cache=true
  sudo: yes
  with_items:
    - php5.6
    - php5.6-fpm
    - redis-server
    - php5.6-cli 
    - php5.6-curl 
    - php5.6-mcrypt 
    - php5.6-mbstring 
    - php5.6-gd 
    - php5.6-intl 
    - php5.6-json 
    - php5.6-dev 
    - php5.6-common 
    - php5.6-iconv 
    - php5.6-dom 
    - php5.6-soap
    - php5.6-memcached
    - composer

- name: template for php.ini
  template:
     src: templates/php.ini
     dest: /etc/php/5.6/fpm/php.ini
     backup: yes
 

